// TODO: license
package minusone.gui;

import java.awt.event.ActionEvent;
import minusone.logic.EventQueueExample;
import minusone.logic.Task;
import minusone.logic.task.SoundPlayingTask;

/**
 *
 * @author Louis-Marie Matthews
 */
public class EventQueueExampleUi
  extends javax.swing.JFrame
{
  private EventQueueExample parentEqe_; // TODO: use interface instead?



  /**
   * Creates new form EventQueueExampleUi
   * @param parentEqe
   */
  public EventQueueExampleUi (EventQueueExample parentEqe) {
      initComponents();

      // Register patern
      parentEqe_ = parentEqe;

      // Add event listeners
      jButton1.addActionListener(this::stillAliveButtonClicked);
      jButton2.addActionListener(this::humanRevolutionButtonClicked);
      jButton3.addActionListener(this::mankindDividedButtonClicked);
      
  }
  
  
  
  private void stillAliveButtonClicked(ActionEvent actionEvent)
  {
    parentEqe_.addTask(new SoundPlayingTask(10, 100, "still-alive.mp3"));
  }
  
  
  
  private void humanRevolutionButtonClicked(ActionEvent actionEvent)
  {
    parentEqe_.addTask(new SoundPlayingTask(10, 100, "human-revolution.mp3"));
  }
  
  
  
  private void mankindDividedButtonClicked(ActionEvent actionEvent)
  {
    parentEqe_.addTask(new SoundPlayingTask(10, 100, "still-alive.mp3"));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Event Queue Example");
    setResizable(false);

    jButton1.setText("Play sound 1");

    jButton2.setText("Play sound 2");

    jButton3.setText("Play sound 3");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButton1)
        .addGap(18, 18, 18)
        .addComponent(jButton2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButton3)
        .addContainerGap(18, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton1)
          .addComponent(jButton2)
          .addComponent(jButton3))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

  public static void createWindow(EventQueueExample parentEqe) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
          for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
              if ("Nimbus".equals(info.getName())) {
                  javax.swing.UIManager.setLookAndFeel(info.getClassName());
                  break;
              }
          }
      } catch (ClassNotFoundException ex) {
          java.util.logging.Logger.getLogger(EventQueueExampleUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
          java.util.logging.Logger.getLogger(EventQueueExampleUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
          java.util.logging.Logger.getLogger(EventQueueExampleUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
          java.util.logging.Logger.getLogger(EventQueueExampleUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
              new EventQueueExampleUi(parentEqe).setVisible(true);
          }
      });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  // End of variables declaration//GEN-END:variables
}